feat: support using Fiammetta to recover others' emotion
Konano/arknights-mower pull request #114
Opened 2022-04-29 11:32 UTC by LingweiMeng

We can use Fiammetta to recover other agents' emotion in a given room now.
The given room should be `room_x_y`
So its input format in the command line is similar to using drones.

And I also change some absolute positions into relative positions in `base_construct.py`.

[reference](https://www.bilibili.com/video/BV1mZ4y1z7wx)

2022-04-29 11:33 UTC, LingweiMeng commented
If you do not have a account to test features of Fiammetta, please contact me.

2022-04-29 16:10 UTC, LingweiMeng commented
> Oh, I forgot to add the image of Fia's Elite 2. I'll test and add it later.
> 
> BTW, if you do not have an account to test the features of Fiammetta, please contact me.

Have added Fiammetta Elite 2 images, and improved the robustness.

2022-05-02 10:35 UTC, Konano commented
You don't need to merge the new commits on the dev branch, which can lead to confusion during review.

2022-05-02 10:47 UTC, Konano commented
Can you force push the two commits `ceb7378700b9b2e67e57416318036bf8bd05c526` and `4c142cc0e1b5d44512604b4f31fa7110fa142079` again?

Rebase maybe can help you.

2022-05-02 22:00 UTC, LingweiMeng commented
> Can you force push the two commits `ceb7378700b9b2e67e57416318036bf8bd05c526` and `4c142cc0e1b5d44512604b4f31fa7110fa142079` again?
> 
> Rebase maybe can help you.

Sorry for the confusion. And thx for reminding me of this.
Is this ok now?

2022-05-03 08:01 UTC, Konano commented on README.md
>  - 自动更换基建排班干员（需要搭配配置文件使用）
```suggestion
- 自动更换基建排班干员（需要搭配配置文件使用）
- 自动使用菲亚梅塔恢复指定房间心情最低干员的心情并重回岗位（工作位置不变以避免重新暖机） [[参考使用场景](https://www.bilibili.com/video/BV1mZ4y1z7wx)]
```

2022-05-03 08:06 UTC, Konano requested changes

2022-05-03 08:06 UTC, Konano commented on arknights_mower/solvers/base_construct.py
> +<<<<<<< HEAD
Unhandled conflicts when merging

2022-05-03 11:58 UTC, LingweiMeng commented on arknights_mower/solvers/base_construct.py
> +<<<<<<< HEAD
Done. Thanks for your help.    :)

2022-05-05 11:13 UTC, Konano commented on arknights_mower/solvers/base_construct.py
> +    def choose_agent_in_order(self, agent: list[str], exclude: list[str] = [], exclude_checked_in: bool = False, dormitory: bool = False):
参数 `exclude` 的默认值最好是 None 而不是空 List，使用空 List 作为默认值会导致多次调用函数时共享同一个 List 变量。

更加详细的说明：https://www.bilibili.com/video/av894493876

2022-05-05 11:26 UTC, Konano approved these changes

2022-05-05 11:27 UTC, merged

2022-05-05 13:21 UTC, LingweiMeng commented on arknights_mower/solvers/base_construct.py
> +    def choose_agent_in_order(self, agent: list[str], exclude: list[str] = [], exclude_checked_in: bool = False, dormitory: bool = False):
谢谢指点